name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # You can specify another version if needed.

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/docs.txt

    - name: Build Sphinx Documentation
      run: |
        cd docsrc
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docsrc/_build/html
        publish_branch: gh-pages
