name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

defaults:
  run:
    shell: bash

env:
  PYTHONUTF8: "1"

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check git is working
        run: |
          git config --global user.email "bumpversion-test-git@github.actions"
          git config --global user.name "Testing Git"
          git --version
          git config --list
      - name: Check mercurial is working
        run: |
          echo -e '[ui]\nusername = Testing Mercurial<bumpversion-test-hg@github.actions>' > ~/.hgrc
          hg --version
      - name: Install test dependencies
        run: pip install -r requirements/test.txt
      - name: Test
        run: pytest --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test-reports/coverage.xml
          flags: python-${{ matrix.python-version }}
          verbose: true # optional (default = false)
          env_vars: OS,PYTHON
